apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-go-calculator-adder
  labels:
    app: add
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add
  template:
    metadata:
      labels:
        app: add
      annotations:
        dapr.io/sidecar-liveness-probe-delay-seconds: "30"
        dapr.io/sidecar-liveness-probe-timeout-seconds: "30"
        dapr.io/sidecar-liveness-probe-period-seconds: "30"
        dapr.io/log-level: "debug"
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-go-calculator-adder"
        dapr.io/app-port: "6000"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: add
        image: localhost:32000/dapr-go-calculator-adder:latest
        env:
          - name: APP_PORT
            value: "6000"
        ports:
        - containerPort: 6000
        imagePullPolicy: Always
